version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: itech-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: itech_db_prod
      MYSQL_USER: itech_user
      MYSQL_PASSWORD: itech_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - itech-network
    restart: unless-stopped

  backend:
    build: .
    container_name: itech-backend
    depends_on:
      - mysql
    environment:
      # Database Configuration
      DATABASE_URL: jdbc:mysql://mysql:3306/itech_db_prod
      DB_USERNAME: itech_user
      DB_PASSWORD: itech_password
      
      # Application Configuration
      SPRING_PROFILES_ACTIVE: production
      PORT: 8080
      
      # JWT Configuration
      JWT_SECRET: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4i5j6k7l8m9n0
      JWT_EXPIRATION: 86400000
      
      # CORS Configuration
      ALLOWED_ORIGINS: http://localhost:3000,https://your-frontend-domain.com
      
      # Email Configuration (Update with your credentials)
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USERNAME: your-email@gmail.com
      SMTP_PASSWORD: your-app-password
      
      # SMS Configuration (Update with your credentials)
      TWILIO_ACCOUNT_SID: your_twilio_sid
      TWILIO_AUTH_TOKEN: your_twilio_token
      TWILIO_PHONE_NUMBER: your_twilio_phone
      
      # Quicko API Configuration (Update with your credentials)
      QUICKO_API_BASE_URL: https://api.quicko.com
      QUICKO_API_KEY: your_quicko_api_key
      QUICKO_API_ENABLED: true
      QUICKO_API_TIMEOUT: 30
      QUICKO_API_RETRY_ATTEMPTS: 3
      QUICKO_API_RETRY_DELAY: 1000
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - itech-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  itech-network:
    driver: bridge
