services:
  # Database Service
  - type: pserv
    name: itech-database
    env: docker
    dockerfilePath: ./postgres.dockerfile
    plan: starter
    region: ohio
    databases:
      - name: itech_db
        user: itech_user
        
  # Web Service
  - type: web
    name: itech-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: ohio
    branch: main
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /health
    numInstances: 1
    
    # Environment Variables
    envVars:
      # Core Configuration
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
        
      # Database Configuration
      # These will be automatically populated from database service
      - key: DATABASE_URL
        fromDatabase:
          name: itech-database
          property: connectionString
      - key: JDBC_DATABASE_URL
        fromDatabase:
          name: itech-database
          property: connectionString
      - key: JDBC_DATABASE_USERNAME
        fromDatabase:
          name: itech-database
          property: user
      - key: JDBC_DATABASE_PASSWORD
        fromDatabase:
          name: itech-database
          property: password
          
      # JWT Configuration
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 86400000
        
      # CORS Configuration
      - key: ALLOWED_ORIGINS
        value: http://localhost:3000,https://your-frontend-domain.com
        
      # Email Configuration
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
        
      # SMS Configuration
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
        
      # Payment Configuration
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: RAZORPAY_WEBHOOK_SECRET
        sync: false
        
      # External API Configuration
      - key: QUICKO_API_BASE_URL
        value: https://api.quicko.com
      - key: QUICKO_API_KEY
        sync: false
      - key: QUICKO_API_ENABLED
        value: true
      - key: QUICKO_API_TIMEOUT
        value: 30
      - key: QUICKO_API_RETRY_ATTEMPTS
        value: 3
      - key: QUICKO_API_RETRY_DELAY
        value: 1000
        
      # Verification API Configuration
      - key: GST_API_URL
        value: https://api.gst-verification.com
      - key: GST_API_KEY
        sync: false
      - key: PAN_API_URL
        value: https://api.pan-verification.com
      - key: PAN_API_KEY
        sync: false
