services:
  - type: web
    name: itech-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: free
    branch: main
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: PORT
        value: 8080
      - key: JAVA_OPTS
        value: "-Xmx1g -Xms512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseStringDeduplication"
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production

databases:
  - name: itech-postgres
    databaseName: itech_db
    user: itech_user
    region: singapore
    plan: free
