spring:
  application:
    name: itech-backend

  # Enable Actuator endpoints
  management:
    endpoints:
      web:
        exposure:
          include: health,prometheus,metrics,info
    endpoint:
      health:
        show-details: always
      metrics:
        enabled: true
      prometheus:
        enabled: true
    metrics:
      export:
        prometheus:
          enabled: true
        tags:
          application: ${spring.application.name}
          environment: ${spring.profiles.active:default}

  # Database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/itech_dev_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata&createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  # Redis configuration
  redis:
    host: localhost
    port: 6379
    timeout: 2000
    database: 0

  # Elasticsearch configuration
  elasticsearch:
    host: localhost
    port: 9200

  # Cache configuration
  cache:
    type: redis
    redis:
      time-to-live: 3600s
      key-prefix: itech_

  # Security configuration
  security:
    jwt:
      secret-key: your-secret-key
      expiration: 86400000 # 24 hours
      refresh-token:
        expiration: 604800000 # 7 days

  # WebSocket configuration
  websocket:
    allowed-origins: http://localhost:3000
    endpoint: /ws
    topics:
      user: /user
      chat: /topic/chat
      notifications: /topic/notifications
